### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by ghost** [jsteinshouer/stock-trader#1]
Hi Jason

Thank you for the code - looking to build from said repo

Quick question how do I build this?

`yarn build` then `yarn dev` ??

When I compare my deployed iteration it seems to lack the functionality that your hosted iteration has. 

- drawer overlapping the navbar
- cant view portfolio

any wisdom you could share?

**Comment by ghost** [comment]
`npm install --save`
`npm run-script dev`

Is this preferred way?

**Comment by jsteinshouer** [comment]
I think you could use Yarn but I just used npm.

This will install dependencies and start a dev server.
```
npm install
npm run dev
```

To build for production run this. 

```
npm run build 
```

**Comment by ghost** [comment]
thank you :)
